//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutritionTest_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableMakanan
    {
        public int Id { get; set; }
        public string NamaMakanan { get; set; }
        public string Kalori { get; set; }
        public string Protein { get; set; }
        public string Karbohidrat { get; set; }
        public string Lemak { get; set; }
        public string Berat { get; set; }
    }
}
